# Site settings
title: SovranistaLocale
email: ecommerce@SovranistaLocale.com
description: Il Sovranista Locale delle Cinque Terre!
baseurl: "/snipcart-jekyll-integration" # the subpath of your site, e.g. /blog/
url: "https://snipcart.github.io" # the base hostname & protocol for your site
logo: images/sovranistalocalenew.jpg
twitter_username: sovranistaloca1
github_username:  danielemoggia
#api_key: YjdiNWIyOTUtZTIyMy00MWMwLTkwNDUtMzI1M2M2NTgxYjE0
api_key: YjU0N2I4MWMtZGVmOC00YzhmLWI2OWMtYjI3MWFjNDRhNGMzNjM3MDEzNjY3NjM1Nzc0MjYx


# Build settings
markdown: kramdown
collections:
  products:
    output: true
